# Generated by Django 5.1.3 on 2024-11-21 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('SST', 'Summarize Spoken Text'), ('RO', 'Re-Order Paragraph'), ('RMMCQ', 'Reading Multiple Choice (Multiple)')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingMultipleChoiceQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passage', models.TextField(help_text='Passage for the RMMCQ question')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rmmcq_details', to='pte_exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderParagraphQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reorder_paragraph_details', to='pte_exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='ReorderParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Content of the paragraph')),
                ('correct_next_order', models.PositiveIntegerField(blank=True, help_text='Order of the correct next paragraph', null=True)),
                ('reorder_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paragraphs', to='pte_exam.reorderparagraphquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RMMCQOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Option text')),
                ('is_correct', models.BooleanField(default=False, help_text='Indicates if this option is correct')),
                ('rmmcq_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='pte_exam.readingmultiplechoicequestion')),
            ],
        ),
        migrations.CreateModel(
            name='SummarizeSpokenText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_time_limit', models.PositiveIntegerField(help_text='Time limit in seconds')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sst_details', to='pte_exam.question')),
            ],
        ),
        migrations.CreateModel(
            name='SSTAudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='audio_files/')),
                ('speaker_name', models.CharField(max_length=255)),
                ('sst_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audio_files', to='pte_exam.summarizespokentext')),
            ],
        ),
    ]
