# Generated by Django 5.1.3 on 2024-11-21 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pte_exam', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RMMCQAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.IntegerField(default=0, help_text='Total score for the question.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pte_exam.readingmultiplechoicequestion')),
                ('selected_options', models.ManyToManyField(help_text='Selected options by the user.', related_name='answers', to='pte_exam.rmmcqoption')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rmmcq_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ROAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paragraph_order', models.JSONField(help_text='Submitted order of paragraph IDs.')),
                ('total_score', models.IntegerField(default=0, help_text='Total score based on correct adjacent pairs.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pte_exam.reorderparagraphquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ro_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SSTAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text="Student's text-based summary.")),
                ('content_score', models.IntegerField(default=0, help_text='Score for content (max 2).')),
                ('form_score', models.IntegerField(default=0, help_text='Score for form (max 2).')),
                ('grammar_score', models.IntegerField(default=0, help_text='Score for grammar (max 2).')),
                ('vocabulary_score', models.IntegerField(default=0, help_text='Score for vocabulary (max 2).')),
                ('spelling_score', models.IntegerField(default=0, help_text='Score for spelling (max 2).')),
                ('total_score', models.IntegerField(default=0, help_text='Total score out of 10.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pte_exam.summarizespokentext')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sst_answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
