# Generated by Django 5.1.3 on 2024-11-22 21:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pte_exam', '0004_alter_rmmcqanswer_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rmmcqanswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='rmmcqanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='roanswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='roanswer',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sstanswer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sstanswer',
            name='user',
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='pte_exam.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rmmcqanswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='rmmcq_answers', to='pte_exam.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roanswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ro_answers', to='pte_exam.answer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sstanswer',
            name='answer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sst_answers', to='pte_exam.answer'),
            preserve_default=False,
        ),
    ]
